name: DEPLOY

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout deploy repository
        uses: actions/checkout@v2
        with:
          repository: aws-amplify-jp/aws-amplify-jp.github.io
          ssh-key: ${{ secrets.ID_ED25519_GITHUB_ACTIONS }}
      - name: deploy
        run: |
          git remote rm origin
          git remote add origin git@github.com:aws-amplify-jp/aws-amplify-jp.github.io.git
          git config --local user.name 'GitHub Actions'
          git config --local user.email 'actions@example.com'
          npm install
          npm run deploy
